spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pinyougoudb?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#项目容器端口
  port: 8080
  application:
    name: microservice-provider-user


#mybatis配置文件位置,以及dao  xxx.xml配置文件
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: cn.xxm.springcloud.pojo


eureka:
  client:  #客户端注册进eureka服务器列表内
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    instance-id: microservice-provider8080   #自定义服务名称信息
    prefer-ip-address: true   #访问路径可以显示IP地址

info:
  app.name: xxm-microservice
  company.name: www.xxm.cn
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}